@startuml

skinparam classAttributeIconSize 0
hide empty attributes
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> Product" {
    entity Product
    class Photo
    class OptionalProductionCode
    class TechnicalDescription
    class BrandName
    class Reference
}

package "<<aggregate>> Category" {
    entity Category
}

package "<<aggregate>> Salesclerk" {
    entity Salesclerk
}

entity Product <<entity>> <<root>> {
    -<<VO>> UniqueInternalCode
    -<<VO>> Barcode
    -<<VO>> ShortDescription
    -<<VO>> ExtendedDescription
    -<<VO>> PriceWithoutTaxes
    -<<VO>> Status /'Available, Temporarily Unavailable, Unavailable'/
    -<<VO>> Weight
    -<<VO>> Volume
    -<<VO>> Tax
}

class TechnicalDescription <<(V,#FF8B40) value object>>
class BrandName <<(V,#FF8B40) value object>>
class Reference <<(V,#FF8B40) value object>>
class Photo <<(V,#FF8B40) value object>>
class OptionalProductionCode <<(V,#FF8B40) value object>>

entity Category <<entity>> <<root>> {
    -<<VO>> AlphanumericCode
    -<<VO>> Description
}

entity Salesclerk <<entity>> <<root>> {
}

Product --> "*" Photo
Product --> "0..1" OptionalProductionCode
Product --> "1" Category : belongs to
Product --> "0..1" TechnicalDescription
Product --> "0..1" BrandName
Product --> "0..1" Reference

Salesclerk --> "1..*" Product

@enduml