@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor WarehouseEmployee as WE
participant ":System" as System

activate WE

WE -> System: wants to access the list of orders that have already been prepared.

activate System

System --> WE: shows agvList and requests to select one agv from the list.

deactivate System

WE -> System: selects one agv from the list.

activate System

System --> WE: shows id of orders processed by the given agv and asks to choose one

deactivate System

WE -> System : selects order from the list

activate System

System -> WE : informs operation success.

deactivate System


deactivate WE

@enduml